# Generated by Django 4.2.26 on 2025-11-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestor.gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.integrante')),
            ],
        ),
    ]
