# Generated by Django 4.2.26 on 2025-11-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_gasto_itemgasto_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='anio_pagado',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuota',
            name='mes_pagado',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=2025, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuota',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gestor.integrante'),
        ),
    ]
