# Generated by Django 4.2.26 on 2025-11-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_cuota_anio_pagado_cuota_mes_pagado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('integrante', 'mes_pagado', 'anio_pagado')},
        ),
    ]
